import { NextResponse } from 'next/server';

interface VercelFile {
  file: string;
  data: string;
}

export async function POST(req: Request) {
  try {
    const { projectName, token, files } = await req.json();

    if (!projectName || !token || !files) {
      return NextResponse.json({ error: 'Données manquantes' }, { status: 400 });
    }

    // 1. Préparation des fichiers
    const deployFiles: VercelFile[] = files.map((f: any) => ({
      file: f.filePath,
      data: f.content
    }));

    // --- AUTO-RÉPARATION : Injection des fichiers système manquants ---
    
    // A. package.json (Si manquant)
    if (!deployFiles.some(f => f.file === 'package.json')) {
        deployFiles.push({
            file: 'package.json',
            data: JSON.stringify({
                name: projectName.toLowerCase().replace(/\s+/g, '-'),
                version: "0.1.0",
                scripts: {
                    "dev": "next dev",
                    "build": "next build",
                    "start": "next start",
                    "lint": "next lint"
                },
                dependencies: {
                    "react": "^18",
                    "react-dom": "^18",
                    "next": "14.2.3", // Version stable
                    "lucide-react": "latest",
                    "clsx": "latest",
                    "tailwind-merge": "latest"
                },
                devDependencies: {
                    "typescript": "^5",
                    "@types/node": "^20",
                    "@types/react": "^18",
                    "@types/react-dom": "^18",
                    "postcss": "^8",
                    "tailwindcss": "^3.4.1",
                    "eslint": "^8",
                    "eslint-config-next": "14.2.3"
                }
            }, null, 2)
        });
    }

    // B. next.config.mjs (Si manquant)
    if (!deployFiles.some(f => f.file.includes('next.config'))) {
        deployFiles.push({
            file: 'next.config.mjs',
            data: `/** @type {import('next').NextConfig} */
const nextConfig = {
    typescript: { ignoreBuildErrors: true },
    eslint: { ignoreDuringBuilds: true },
    images: { unoptimized: true }
};
export default nextConfig;`
        });
    }

    // C. app/layout.tsx (CRUCIAL : Obligatoire pour Next.js App Router)
    // On vérifie si un layout existe déjà dans app/ ou src/app/
    const hasLayout = deployFiles.some(f => f.file.includes('layout.tsx') || f.file.includes('layout.js'));
    
    if (!hasLayout) {
        deployFiles.push({
            file: 'app/layout.tsx', // On force le chemin App Router
            data: `import React from 'react';
import './globals.css';

export const metadata = {
  title: '${projectName}',
  description: 'Generated by Studio Code',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}`
        });
    }
    
    // D. app/globals.css (Si manquant, pour le style de base)
    if (!deployFiles.some(f => f.file.includes('globals.css'))) {
         deployFiles.push({
            file: 'app/globals.css',
            data: `@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  background: #ffffff;
  color: #000000;
}`
         });
    }

    // 2. Création du déploiement sur Vercel
    const response = await fetch('https://api.vercel.com/v13/deployments', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        name: projectName.toLowerCase().replace(/\s+/g, '-'),
        files: deployFiles,
        projectSettings: {
          framework: 'nextjs',
        },
        target: 'production',
      }),
    });

    const data = await response.json();

    if (!response.ok) {
      return NextResponse.json({ success: false, error: data.error?.message || 'Erreur Vercel' }, { status: 500 });
    }

    return NextResponse.json({ 
        success: true, 
        deploymentId: data.id,
        url: data.url 
    });

  } catch (error: any) {
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  }
      }
