import { NextResponse } from 'next/server';

export const runtime = 'nodejs';

export async function POST(req: Request) {
  const encoder = new TextEncoder();

  const stream = new ReadableStream({
    async start(controller) {
      const sendLog = (message: string, type: 'info' | 'success' | 'error' | 'warning' = 'info') => {
        const logEntry = JSON.stringify({ message, type, timestamp: new Date().toLocaleTimeString() });
        controller.enqueue(encoder.encode(logEntry + '\n'));
      };

      try {
        const { token, repoName, branch = 'main', commitMessage = 'Update via Studio Code', files } = await req.json();

        if (!token || !repoName || !files) {
          sendLog('Missing required fields', 'error');
          controller.close();
          return;
        }

        sendLog('Authenticating with GitHub...', 'info');
        const userRes = await fetch('https://api.github.com/user', {
            headers: { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github.v3+json' }
        });
        
        if (!userRes.ok) throw new Error('Invalid GitHub Token');
        const user = await userRes.json();
        sendLog(`Authenticated as: ${user.login}`, 'success');

        let repoFullName = `${user.login}/${repoName}`;
        sendLog(`Checking repository: ${repoFullName}...`, 'info');
        
        const repoCheck = await fetch(`https://api.github.com/repos/${repoFullName}`, {
            headers: { Authorization: `Bearer ${token}` }
        });

        if (repoCheck.status === 404) {
            sendLog(`Repository '${repoName}' not found. Creating...`, 'warning');
            const createRes = await fetch('https://api.github.com/user/repos', {
                method: 'POST',
                headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
                body: JSON.stringify({ name: repoName, private: true, auto_init: true })
            });
            
            if (!createRes.ok) throw new Error('Failed to create repository');
            sendLog(`Repository '${repoName}' created successfully.`, 'success');
            
            await new Promise(r => setTimeout(r, 2000));
        } else {
            sendLog(`Repository '${repoName}' found.`, 'success');
        }

        const filesMap = new Map(files.map((f: any) => [
            f.filePath.startsWith('/') ? f.filePath.substring(1) : f.filePath, 
            f.content
        ]));

        if (!filesMap.has('package.json')) {
            sendLog('Injecting missing package.json...', 'warning');
            filesMap.set('package.json', JSON.stringify({ name: repoName, version: "0.1.0", dependencies: { "next": "latest", "react": "latest", "react-dom": "latest" } }, null, 2));
        }
        if (!filesMap.has('README.md')) {
             filesMap.set('README.md', `# ${repoName}\n\nGenerated by Studio Code.`);
        }

        sendLog(`Fetching branch '${branch}' reference...`, 'info');
        let baseTreeSha = null;
        let parentCommitSha = null;

        const refRes = await fetch(`https://api.github.com/repos/${repoFullName}/git/refs/heads/${branch}`, {
            headers: { Authorization: `Bearer ${token}` }
        });

        if (refRes.ok) {
            const refData = await refRes.json();
            parentCommitSha = refData.object.sha;
            
            const commitRes = await fetch(`https://api.github.com/repos/${repoFullName}/git/commits/${parentCommitSha}`, {
                headers: { Authorization: `Bearer ${token}` }
            });
            const commitData = await commitRes.json();
            baseTreeSha = commitData.tree.sha;
            sendLog(`Base commit found: ${parentCommitSha.substring(0, 7)}`, 'info');
        } else {
            sendLog(`Branch '${branch}' not found. Starting fresh commit history.`, 'warning');
        }

        sendLog(`Uploading ${filesMap.size} files...`, 'info');
        const treeItems = [];

        for (const [path, content] of filesMap.entries()) {
            const blobRes = await fetch(`https://api.github.com/repos/${repoFullName}/git/blobs`, {
                method: 'POST',
                headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
                body: JSON.stringify({ content: content, encoding: 'utf-8' })
            });

            if (!blobRes.ok) {
                sendLog(`Failed to upload file: ${path}`, 'error');
                continue;
            }

            const blobData = await blobRes.json();
            treeItems.push({
                path: path,
                mode: '100644',
                type: 'blob',
                sha: blobData.sha
            });
        }
        sendLog(`All blobs created successfully.`, 'success');

        sendLog('Building git tree...', 'info');
        const treePayload: any = { tree: treeItems };
        if (baseTreeSha) treePayload.base_tree = baseTreeSha;

        const treeRes = await fetch(`https://api.github.com/repos/${repoFullName}/git/trees`, {
            method: 'POST',
            headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
            body: JSON.stringify(treePayload)
        });

        if (!treeRes.ok) throw new Error('Failed to create git tree');
        const treeData = await treeRes.json();

        sendLog('Creating commit...', 'info');
        const commitPayload: any = {
            message: commitMessage,
            tree: treeData.sha,
            parents: parentCommitSha ? [parentCommitSha] : []
        };

        const newCommitRes = await fetch(`https://api.github.com/repos/${repoFullName}/git/commits`, {
            method: 'POST',
            headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
            body: JSON.stringify(commitPayload)
        });

        if (!newCommitRes.ok) throw new Error('Failed to create commit');
        const newCommitData = await newCommitRes.json();

        sendLog(`Pushing to ${branch}...`, 'info');
        const refPayload = {
            sha: newCommitData.sha,
            force: true
        };

        const updateRefMethod = parentCommitSha ? 'PATCH' : 'POST';
        const updateRefUrl = parentCommitSha 
            ? `https://api.github.com/repos/${repoFullName}/git/refs/heads/${branch}`
            : `https://api.github.com/repos/${repoFullName}/git/refs`;
        
        const finalBody = parentCommitSha 
            ? JSON.stringify(refPayload)
            : JSON.stringify({ ref: `refs/heads/${branch}`, sha: newCommitData.sha });

        const pushRes = await fetch(updateRefUrl, {
            method: updateRefMethod,
            headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
            body: finalBody
        });

        if (!pushRes.ok) throw new Error('Failed to push reference');
        
        sendLog('🚀 Code successfully pushed to GitHub!', 'success');
        
        const endMsg = JSON.stringify({ 
            message: 'DONE', 
            type: 'DONE', 
            url: `https://github.com/${repoFullName}` 
        });
        controller.enqueue(encoder.encode(endMsg));

      } catch (error: any) {
        sendLog(`CRITICAL ERROR: ${error.message}`, 'error');
      } finally {
        controller.close();
      }
    }
  });

  return new Response(stream, {
    headers: { 'Content-Type': 'text/plain; charset=utf-8' },
  });
               }
